import 'package:iconsax/iconsax.dart';
import 'package:tajweed_book_app/models/menu_model.dart';

import '../../models/section_model.dart';

class AppLists {
  AppLists._();

  // Menu List
  static const List<MenuModel> homeMenu = [
    // MenuModel(
    //   id: 1,
    //   title: "عن الكتاب",
    //   icon: Iconsax.book,
    // ),
    MenuModel(
      id: 2,
      title: "عن المؤلف",
      icon: Iconsax.personalcard,
    ),
    // MenuModel(
    //   id: 3,
    //   title: "القنوات الدعوية",
    //   icon: Iconsax.link_circle,
    // ),
    MenuModel(
      id: 4,
      title: "المفضلة",
      icon: Iconsax.bookmark,
    ),
    // MenuModel(
    //   id: 5,
    //   title: "المطور",
    //   icon: Iconsax.code_1,
    // ),
    MenuModel(
      id: 5,
      title: "شارك التطبيق",
      icon: Iconsax.share,
    ),
    // MenuModel(
    //   id: 6,
    //   title: "تقييم التطبيق",
    //   icon: Iconsax.star,
    // ),
  ];

  // Table Of Contents
  static const List<SectionModel> tableOfContents = [
    SectionModel(
      id: 1,
      title: "ترجمة المؤلف",
      type: 1,
      pageNumber: 6,
      pageLastNumber: 9,
    ),
    SectionModel(
      id: 2,
      title: "المقدمة",
      type: 1,
      pageNumber: 10,
      pageLastNumber: 10,
    ),
    SectionModel(
      id: 3,
      title: "ملخص التجويد",
      type: 1,
      pageNumber: 11,
      pageLastNumber: 16,
    ),
    SectionModel(
      id: 4,
      title: "البسملة",
      type: 2,
      pageNumber: 17,
      pageLastNumber: 18,
    ),
    SectionModel(
      id: 5,
      title: "مراتب التلاوة",
      type: 2,
      pageNumber: 19,
      pageLastNumber: 19,
    ),
    SectionModel(
      id: 6,
      title: "اللحن",
      type: 2,
      pageNumber: 20,
      pageLastNumber: 20,
    ),
    SectionModel(
      id: 7,
      title: "الأسئلة",
      type: 2,
      pageNumber: 21,
      pageLastNumber: 24,
    ),
    SectionModel(
      id: 8,
      title: "والناس في قراءتهم للقرآن ثلاثة",
      type: 2,
      pageNumber: 25,
      pageLastNumber: 25,
    ),
    SectionModel(
      id: 9,
      title: "أحكام النون الساكنة والتنوين ",
      type: 1,
      pageNumber: 26,
      pageLastNumber: 26,
    ),
    SectionModel(
      id: 10,
      title: "الإظهار",
      type: 2,
      pageNumber: 27,
      pageLastNumber: 27,
    ),
    SectionModel(
      id: 11,
      title: "الإدغام",
      type: 2,
      pageNumber: 28,
      pageLastNumber: 29,
    ),
    SectionModel(
      id: 12,
      title: "الإدغام وأنواعه ",
      type: 3,
      pageNumber: 30,
      pageLastNumber: 32,
    ),
    SectionModel(
      id: 13,
      title: "الإخفاء الحقيقي",
      type: 2,
      pageNumber: 33,
      pageLastNumber: 34,
    ),
    SectionModel(
      id: 14,
      title: "الإقلاب",
      type: 2,
      pageNumber: 35,
      pageLastNumber: 35,
    ),
    SectionModel(
      id: 15,
      title: "الإخفاء الشفوي",
      type: 2,
      pageNumber: 35,
      pageLastNumber: 35,
    ),
    SectionModel(
      id: 16,
      title: "٢ - الإدغام الشفوي",
      type: 2,
      pageNumber: 36,
      pageLastNumber: 36,
    ),
    SectionModel(
      id: 17,
      title: "الإظهار الشفوي",
      type: 2,
      pageNumber: 36,
      pageLastNumber: 36,
    ),
    SectionModel(
      id: 18,
      title: "الحروف القمرية",
      type: 2,
      pageNumber: 37,
      pageLastNumber: 37,
    ),
    SectionModel(
      id: 19,
      title: "أحكام المد",
      type: 1,
      pageNumber: 38,
      pageLastNumber: 39,
    ),
    SectionModel(
      id: 20,
      title: "المد الفرعي",
      type: 2,
      pageNumber: 40,
      pageLastNumber: 41,
    ),
    SectionModel(
      id: 21,
      title: "واجب بدل",
      type: 2,
      pageNumber: 42,
      pageLastNumber: 44,
    ),
    SectionModel(
      id: 22,
      title: "مد الصلة الصغرى",
      type: 2,
      pageNumber: 45,
      pageLastNumber: 45,
    ),
    SectionModel(
      id: 23,
      title: "مد التمكين",
      type: 2,
      pageNumber: 46,
      pageLastNumber: 49,
    ),
    SectionModel(
      id: 24,
      title: "الوقف وانواعه وأحكامه",
      type: 2,
      pageNumber: 50,
      pageLastNumber: 54,
    ),
    SectionModel(
      id: 25,
      title: "وقف البيان الكافي",
      type: 2,
      pageNumber: 55,
      pageLastNumber: 55,
    ),
    SectionModel(
      id: 26,
      title: "الوقف الحسن",
      type: 2,
      pageNumber: 56,
      pageLastNumber: 56,
    ),
    SectionModel(
      id: 27,
      title: "الوقف القبيح",
      type: 2,
      pageNumber: 57,
      pageLastNumber: 57,
    ),
    SectionModel(
      id: 28,
      title: "الابتداء",
      type: 2,
      pageNumber: 58,
      pageLastNumber: 58,
    ),
    SectionModel(
      id: 29,
      title: "الفرق بين همزة الوصل وهمزة القطع",
      type: 2,
      pageNumber: 59,
      pageLastNumber: 59,
    ),
    SectionModel(
      id: 30,
      title: "مقدمة في الحروف",
      type: 1,
      pageNumber: 60,
      pageLastNumber: 60,
    ),
    SectionModel(
      id: 31,
      title: "مخارج الحروف الأصلية",
      type: 2,
      pageNumber: 61,
      pageLastNumber: 62,
    ),
    SectionModel(
      id: 32,
      title: "المخرج الأول: الجوف",
      type: 2,
      pageNumber: 63,
      pageLastNumber: 63,
    ),
    SectionModel(
      id: 33,
      title: "المخرج الثاني: الحلق",
      type: 2,
      pageNumber: 64,
      pageLastNumber: 64,
    ),
    SectionModel(
      id: 34,
      title: "المخرج الثالث: اللسان",
      type: 2,
      pageNumber: 65,
      pageLastNumber: 67,
    ),
    SectionModel(
      id: 35,
      title: "المخرج الرابع: الشفتان",
      type: 2,
      pageNumber: 68,
      pageLastNumber: 68,
    ),
    SectionModel(
      id: 36,
      title: "المخرج الخامس: الخيشوم",
      type: 2,
      pageNumber: 69,
      pageLastNumber: 69,
    ),
    SectionModel(
      id: 37,
      title: "ألقاب الحروف",
      type: 2,
      pageNumber: 69,
      pageLastNumber: 70,
    ),
    SectionModel(
      id: 38,
      title: "مخارج الحروف الفرعية",
      type: 2,
      pageNumber: 71,
      pageLastNumber: 72,
    ),
    SectionModel(
      id: 39,
      title: "الصفة",
      type: 2,
      pageNumber: 73,
      pageLastNumber: 73,
    ),
    SectionModel(
      id: 40,
      title: "فوائد معرفة الصفات",
      type: 3,
      pageNumber: 73,
      pageLastNumber: 73,
    ),
    SectionModel(
      id: 41,
      title: "تنقسم الصفات إلى قسمين",
      type: 3,
      pageNumber: 74,
      pageLastNumber: 74,
    ),
    SectionModel(
      id: 42,
      title: "الصفات الأصلية",
      type: 3,
      pageNumber: 74,
      pageLastNumber: 74,
    ),
    SectionModel(
      id: 43,
      title: "أولاً : الصفات التي لها ضد:",
      type: 3,
      pageNumber: 75,
      pageLastNumber: 85,
    ),
    SectionModel(
      id: 44,
      title: "ثانياً: الصفات التي لا ضد لها",
      type: 3,
      pageNumber: 86,
      pageLastNumber: 91,
    ),
    SectionModel(
      id: 45,
      title: "أقسام الصفات من حيث القوة والضعف",
      type: 3,
      pageNumber: 92,
      pageLastNumber: 92,
    ),
    SectionModel(
      id: 46,
      title: "عملية استخراج الصفات",
      type: 3,
      pageNumber: 93,
      pageLastNumber: 95,
    ),
    SectionModel(
      id: 47,
      title: "الصفات العارضة",
      type: 3,
      pageNumber: 96,
      pageLastNumber: 96,
    ),
    SectionModel(
      id: 48,
      title: "والحروف المفخمة، بصفة دائمة",
      type: 3,
      pageNumber: 96,
      pageLastNumber: 97,
    ),
    SectionModel(
      id: 49,
      title: "الخاتمة",
      type: 1,
      pageNumber: 98,
      pageLastNumber: 98,
    ),
  ];
}
